version: '3'
services:
  jupyter:
    container_name: jupyter_notebook_container_ads
    image: jupyter/datascience-notebook
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: always

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=adschief1
      - POSTGRES_PASSWORD=1eYvmDnMPikKSImeLrev
      - POSTGRES_DB=adsdatabase
    restart: always